### ISSUE TITLE
Another crash for you (1.10.2 large modpack) 

### ISSUE THREAD

**Issue by bigrice1018** [asiekierka/ClassCacheTweakerMC#2]
Using class cache tweaker version 0.1.1
[crash-2017-03-13_12.25.44-client.txt](https://github.com/asiekierka/ClassCacheTweakerMC/files/837294/crash-2017-03-13_12.25.44-client.txt)

**Comment by asiekierka** [comment]
Could you please try with 0.1.2?

**Comment by bigrice1018** [comment]
Instant response OAO
Tested and no crash
startup time 3:48 -> 3:12
Thx~
