### ISSUE TITLE
Error patching func_72939_s in net.minecraft.world.World

### ISSUE THREAD

**Issue by Ristovski** [asiekierka/ClassCacheTweakerMC#7]
Using the latest forge (1.11.2 - 13.20.0.2282) with 1.11.2 causes the following lengthy error: https://bpaste.net/raw/04b2f3795ac0

**Comment by asiekierka** [comment]
Nallar's JavaPatcher is not compatible with ClassCacheTweaker at this time.

**Comment by LunNova** [comment]
Should be fixed now, update TickProfiler and try again.

**Comment by asiekierka** [comment]
@nallar Actually, I think I blacklisted your transformer (thereby making it not cached) in 0.1.4 already. Whoops! I might whitelist it if I ever look into CCT again, though...

**Comment by Ristovski** [comment]
@asiekierka _"if I ever look into CCT again"_ - Unacceptable, it is your duty :cry:
